use sqlx::prelude::FromRow;

#[derive(FromRow)]
pub(crate) struct BoardRow {
    pub(crate) id: String,
    pub(crate) name: String,
    pub(crate) info: String,
    pub(crate) info_outer: String,
    pub(crate) male_adjectives: String,
    pub(crate) male_proper_names: String,
    pub(crate) female_adjectives: String,
    pub(crate) female_proper_names: String,
    pub(crate) reactions: String,
    pub(crate) category_id: i32,
    pub(crate) default_name: String,
    pub(crate) enable_dices: bool,
    pub(crate) enable_flags: bool,
    pub(crate) enable_icons: bool,
    pub(crate) enable_likes: bool,
    pub(crate) enable_reactions: bool,
    pub(crate) enable_names: bool,
    pub(crate) enable_ids: bool,
    pub(crate) enable_oekaki: bool,
    pub(crate) enable_posting: bool,
    pub(crate) enable_sage: bool,
    pub(crate) enable_shield: bool,
    pub(crate) enable_subject: bool,
    pub(crate) enable_thread_tags: bool,
    pub(crate) enable_trips: bool,
    pub(crate) enable_op_mod: bool,
    pub(crate) enable_telegram_linking: bool,
    pub(crate) require_files_for_op: bool,
    pub(crate) is_danger: bool,
    pub(crate) file_types: String,
    pub(crate) bump_limit: i32,
    pub(crate) last_num: i32,
    pub(crate) max_comment: i32,
    pub(crate) max_files_size: i32,
    pub(crate) max_pages: i32,
    pub(crate) speed: i32,
    pub(crate) threads: i32,
    pub(crate) threads_per_page: i32,
    pub(crate) unique_posters: i32,
    pub(crate) ban_reasons: Option<String>,
    pub(crate) spamlist: Option<String>,
    pub(crate) replacements: Option<String>,
    pub(crate) deleted: i32,
}
